substitutions:
  _AGENT_LOCS: "us-central1 europe-west3 asia-northeast1 asia-southeast1 us-east1 us-west1 australia-southeast1 southamerica-east1"

steps:
  # Build agent image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/gcp-mon-backend/agent:latest', './agent']

  # Push agent image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/gcp-mon-backend/agent:latest']

  # Deploy agents to multiple locations (up to 5 successful regions)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        echo "Agent locations: $_AGENT_LOCS"
        SUCCESS=0
        MAX=5

        for LOC in ${_AGENT_LOCS}; do
          if [ "$SUCCESS" -ge "$MAX" ]; then
            echo "✅ Reached $MAX successful deployments. Stopping."
            break
          fi

          SERVICE_NAME="gcp-mon-agent-${LOC}"
          IMAGE="asia-south1-docker.pkg.dev/$PROJECT_ID/gcp-mon-backend/agent:latest"

          echo "🚀 Deploying $SERVICE_NAME to $LOC"

          if gcloud run deploy "$SERVICE_NAME" \
              --image "$IMAGE" \
              --region "$LOC" \
              --platform managed \
              --allow-unauthenticated \
              --service-account cloud-run-gcp-mon@gcp-mon-472905.iam.gserviceaccount.com \
              --set-env-vars=REGION="$LOC"; then

            URL=$(gcloud run services describe "$SERVICE_NAME" \
              --platform managed \
              --region "$LOC" \
              --format 'value(status.url)')

            gcloud run services update "$SERVICE_NAME" \
              --region "$LOC" \
              --update-env-vars=K_SERVICE_URL="$URL",REGION="$LOC"

            SUCCESS=$((SUCCESS+1))
            echo "✅ Successfully deployed to $LOC ($SUCCESS/$MAX)"
          else
            echo "⚠️ Failed to deploy to $LOC (skipping)"
            continue
          fi
        done

  # Build collector image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/gcp-mon-backend/collector:latest', './collector']

  # Push collector image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/gcp-mon-backend/collector:latest']

  # Deploy collector (Mumbai only)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        LOC=asia-south1
        SERVICE_NAME=gcp-mon-collector
        IMAGE=asia-south1-docker.pkg.dev/$PROJECT_ID/gcp-mon-backend/collector:latest

        echo "🚀 Deploying $SERVICE_NAME to $LOC"

        gcloud run deploy "$SERVICE_NAME" \
          --image "$IMAGE" \
          --region "$LOC" \
          --platform managed \
          --allow-unauthenticated \
          --service-account cloud-run-gcp-mon@gcp-mon-472905.iam.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY
