substitutions:
  _AGENT_LOCS: "us-east1 us-central1 europe-west1"

steps:
  # Build agent image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/gcp-mon-backend/agent:latest', './agent']

  # Push agent image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/gcp-mon-backend/agent:latest']

  # Deploy agents
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        echo "Agent locations: $_AGENT_LOCS"

        SUCCESS_COUNT=0
        MAX_REGIONS=3   # reduce for quota safety

        for LOC in ${_AGENT_LOCS}; do
          if [ $SUCCESS_COUNT -ge $MAX_REGIONS ]; then
            echo "✅ Reached max regions ($MAX_REGIONS). Stopping."
            break
          fi

          SERVICE_NAME=gcp-mon-agent-$LOC
          IMAGE=asia-south1-docker.pkg.dev/$PROJECT_ID/gcp-mon-backend/agent:latest

          echo "🚀 Deploying $SERVICE_NAME to $LOC"

          if gcloud run deploy $SERVICE_NAME \
            --image $IMAGE \
            --region $LOC \
            --platform managed \
            --allow-unauthenticated \
            --service-account cloud-run-gcp-mon@$PROJECT_ID.iam.gserviceaccount.com \
            --set-env-vars=REGION=$LOC \
            --verbosity=debug; then

            URL=$(gcloud run services describe $SERVICE_NAME \
              --platform managed \
              --region $LOC \
              --format 'value(status.url)')

            gcloud run services update $SERVICE_NAME \
              --region $LOC \
              --update-env-vars=K_SERVICE_URL=$URL,REGION=$LOC

            SUCCESS_COUNT=$((SUCCESS_COUNT+1))
            echo "✅ Successfully deployed to $LOC (Total: $SUCCESS_COUNT)"
          else
            echo "⚠️ Skipping $LOC due to error (likely quota)."
            continue
          fi
        done

  # Build & push collector
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/gcp-mon-backend/collector:latest', './collector']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/gcp-mon-backend/collector:latest']

  # Deploy collector (Mumbai)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        LOC=asia-south1
        SERVICE_NAME=gcp-mon-collector
        IMAGE=asia-south1-docker.pkg.dev/$PROJECT_ID/gcp-mon-backend/collector:latest

        echo "🚀 Deploying $SERVICE_NAME to $LOC"

        gcloud run deploy $SERVICE_NAME \
          --image $IMAGE \
          --region $LOC \
          --platform managed \
          --allow-unauthenticated \
          --service-account cloud-run-gcp-mon@$PROJECT_ID.iam.gserviceaccount.com \
          --verbosity=debug

options:
  logging: CLOUD_LOGGING_ONLY
