substitutions:
  _AGENT_LOCS: "us-central1 europe-west3 asia-northeast1 asia-southeast1 asia-south1"

steps:
  # Build agent image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/latency/agent:latest', './agent']

  # Push agent image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/latency/agent:latest']

  # Deploy agents to multiple locations
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        for LOC in ${_AGENT_LOCS}; do
          SERVICE_NAME=latency-agent-${LOC}
          IMAGE=asia-south1-docker.pkg.dev/$PROJECT_ID/latency/agent:latest

          echo "🚀 Deploying $SERVICE_NAME to $LOC"

          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE \
            --region $LOC \
            --platform managed \
            --allow-unauthenticated \
            --service-account cloud-run-gcp-mon@gcp-mon.iam.gserviceaccount.com \
            --set-env-vars=LOC=${LOC}

          URL=$(gcloud run services describe $SERVICE_NAME \
            --platform managed \
            --region $LOC \
            --format 'value(status.url)')

          gcloud run services update $SERVICE_NAME \
            --region $LOC \
            --update-env-vars=K_SERVICE_URL=${URL},LOC=${LOC}
        done

  # Build collector image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/latency/collector:latest', './collector']

  # Push collector image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/latency/collector:latest']

  # Deploy collector (Mumbai only)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        LOC=asia-south1
        SERVICE_NAME=latency-collector
        IMAGE=asia-south1-docker.pkg.dev/$PROJECT_ID/latency/collector:latest

        echo "🚀 Deploying $SERVICE_NAME to $LOC"

        gcloud run deploy $SERVICE_NAME \
          --image $IMAGE \
          --region $LOC \
          --platform managed \
          --allow-unauthenticated \
          --service-account cloud-run-gcp-mon@gcp-mon.iam.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY
