substitutions:
  _AGENT_LOCS: "us-central1 europe-west3 asia-northeast1 asia-southeast1 asia-south1"

steps:
  # Build agent image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/gcp-mon-backend/agent:latest', './agent']

  # Push agent image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/gcp-mon-backend/agent:latest']

  # Deploy agents to multiple locations
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        echo "Agent locations: $_AGENT_LOCS"
        for LOC in ${_AGENT_LOCS}; do
          declare -p LOC
          echo "printtest -- loc : $$LOC"
          _SERVICE_NAME=gcp-mon-agent-$$LOC
          _IMAGE=asia-south1-docker.pkg.dev/$PROJECT_ID/gcp-mon-backend/agent:latest

          echo "🚀 Deploying $_SERVICE_NAME to $$LOC"

          gcloud run deploy $_SERVICE_NAME \
            --image $_IMAGE \
            --region $$LOC \
            --platform managed \
            --allow-unauthenticated \
            --service-account cloud-run-gcp-mon@gcp-mon.iam.gserviceaccount.com \
            --set-env-vars=REGION=$$LOC

          _URL=$(gcloud run services describe $_SERVICE_NAME \
            --platform managed \
            --region $$LOC \
            --format 'value(status.url)')

          gcloud run services update $_SERVICE_NAME \
            --region $$LOC \
            --update-env-vars=K_SERVICE_URL=$_URL,REGION=$$LOC
        done

  # Build collector image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/gcp-mon-backend/collector:latest', './collector']

  # Push collector image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/gcp-mon-backend/collector:latest']

  # Deploy collector (Mumbai only)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        LOC=asia-south1
        _SERVICE_NAME=gcp-mon-collector
        _IMAGE=asia-south1-docker.pkg.dev/$PROJECT_ID/gcp-mon-backend/collector:latest

        echo "🚀 Deploying $_SERVICE_NAME to $$LOC"

        gcloud run deploy $_SERVICE_NAME \
          --image $_IMAGE \
          --region $$LOC \
          --platform managed \
          --allow-unauthenticated \
          --service-account cloud-run-gcp-mon@gcp-mon.iam.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY
