substitutions:
  _AGENT_LOCS: "us-central1 europe-west3 asia-northeast1 asia-southeast1 asia-south1"

steps:
  # Build agent image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/gcp-mon-backend/agent:latest', './agent']

  # Push agent image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/gcp-mon-backend/agent:latest']

  # Deploy agents to multiple locations
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        echo "Agent locations: $_AGENT_LOCS"
        for loc in "$@"; do
          SERVICE_NAME="gcp-mon-agent-${loc}"
          IMAGE="asia-south1-docker.pkg.dev/$PROJECT_ID/gcp-mon-backend/agent:latest"

          echo "🚀 Deploying ${SERVICE_NAME} to ${loc}"

          gcloud run deploy "${SERVICE_NAME}" \
            --image "${IMAGE}" \
            --region "${loc}" \
            --platform managed \
            --allow-unauthenticated \
            --service-account cloud-run-gcp-mon@gcp-mon.iam.gserviceaccount.com \
            --set-env-vars="REGION=${loc}"

          URL=$(gcloud run services describe "${SERVICE_NAME}" \
            --platform managed \
            --region "${loc}" \
            --format 'value(status.url)')

          echo "Updating ${SERVICE_NAME} with URL: ${URL}"
          
          gcloud run services update "${SERVICE_NAME}" \
            --region "${loc}" \
            --update-env-vars="K_SERVICE_URL=${URL},REGION=${loc}"
        done
      - 'bash' # This tells bash to treat the next arguments as positional parameters
      - ${_AGENT_LOCS} # This passes the list of locations as arguments

  # Build collector image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/gcp-mon-backend/collector:latest', './collector']

  # Push collector image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/gcp-mon-backend/collector:latest']

  # Deploy collector (Mumbai only)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        _LOC=asia-south1
        _SERVICE_NAME=gcp-mon-collector
        _IMAGE=asia-south1-docker.pkg.dev/$PROJECT_ID/gcp-mon-backend/collector:latest

        echo "🚀 Deploying $_SERVICE_NAME to $_LOC"

        gcloud run deploy $_SERVICE_NAME \
          --image $_IMAGE \
          --region $_LOC \
          --platform managed \
          --allow-unauthenticated \
          --service-account cloud-run-gcp-mon@gcp-mon.iam.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY
